
export const voices = [
    {value: "つくよみちゃん-れいせい", label: 'つくよみちゃん'},
    {value: "おふとんP-のーまるv2", label: 'おふとんP'},
    {value: "MANA-のーまる", label: 'MANA'},
    {value: "MANA+-ないしょばなし", label: 'MANA+-ないしょばなし'},
    {value: "KANA-のーまる", label: 'KANA'},
    {value: "ディアちゃん-のーまる", label: 'ディアちゃん'},
    {value: "アルマちゃん-表-v2", label: 'アルマちゃん'},
    {value: "AI声優-朱花-のーまる", label: 'AI声優-朱花'},
    {value: "AI声優-青葉-のーまる", label: 'AI声優-青葉'},
    {value: "AI声優-銀芽-のーまる", label: 'AI声優-銀芽'},
    {value: "伊能いお-ふつう", label: '伊能いお'},
    {value: "あみたろ-のーまるv4", label: 'あみたろ'},
    {value: "お星-テンション↑↑", label: 'お星'},
    {value: "四国めたん-ノーマル", label: '四国めたん'},
    {value: "ずんだもん-ノーマル", label: 'ずんだもん'},
    {value: "ずんだもん-ヒソヒソ", label: 'ずんだもん-ヒソヒソ'},
    {value: "春日部つむぎ-ノーマル", label: '春日部つむぎ'},
    {value: "雨晴はう-ノーマル", label: '雨晴はう'},
    {value: "波音リツ-ノーマル", label: '波音リツ'},
    {value: "玄野武宏-ノーマル", label: '玄野武宏'},
    {value: "白上虎太郎-ふつう", label: '白上虎太郎'},
    {value: "青山龍星-ノーマル", label: '青山龍星'},
    {value: "冥鳴ひまり-ノーマル", label: '冥鳴ひまり'},
    {value: "九州そら-ノーマル", label: '九州そら'},
    {value: "剣崎雌雄-ノーマル", label: '剣崎雌雄'},
    {value: "WhiteCUL-ノーマル", label: 'WhiteCUL'},
    {value: "後鬼-人間ver.", label: '後鬼-人間ver.'},
    {value: "ちび式じい-ノーマル", label: 'ちび式じい'},
    {value: "櫻歌ミコ-ノーマル", label: '櫻歌ミコ'},
    {value: "小夜/SAYO-ノーマル", label: '小夜/SAYO'},
    {value: "ナースロボ＿タイプＴ-ノーマル", label: 'ナースロボ＿タイプＴ'},
    {value: "†聖騎士 紅桜†-ノーマル", label: '†聖騎士 紅桜†'},
    {value: "雀松朱司-ノーマル", label: '雀松朱司'},
    {value: "麒ヶ島宗麟-ノーマル", label: '麒ヶ島宗麟'},
    {value: "春歌ナナ-ノーマル", label: '春歌ナナ'},
    {value: "猫使アル-ノーマル", label: '猫使アル'},
    {value: "猫使ビィ-ノーマル", label: '猫使ビィ'},
    {value: "#ランダム", label: '#ランダム'},
]

