#[derive(Copy, Clone)]
pub enum Voice {
    Tsukuyomichan = 0,
    Oftonp        = 1,
    Mana          = 2,
    Kana          = 3,
    Shikokumetan  = 4,
    Zundamon      = 5,
}

impl TryFrom<&String> for Voice {
    type Error = ();

    fn try_from(v: &String) -> Result<Self, Self::Error> {
        match v {
            x if x == "つくよみちゃん" => Ok(Voice::Tsukuyomichan),
            x if x == "おふとんP" => Ok(Voice::Oftonp),
            x if x == "MANA" => Ok(Voice::Mana),
            x if x == "KANA" => Ok(Voice::Kana),
            x if x == "四国めたん" => Ok(Voice::Shikokumetan),
            x if x == "ずんだもん" => Ok(Voice::Zundamon),
            _ => Err(()),
        }
    }
}

pub struct PresetVoice {
    data: Vec<Vec<u8>>
}

impl PresetVoice {
    pub fn new() -> Self {
        PresetVoice { data: vec![
            include_bytes!("../../resource/00-tsukuyomichan/0時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/1時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/2時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/3時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/4時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/5時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/6時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/7時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/8時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/9時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/10時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/11時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/12時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/13時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/14時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/15時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/16時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/17時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/18時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/19時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/20時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/21時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/22時です.wav").to_vec(),
            include_bytes!("../../resource/00-tsukuyomichan/23時です.wav").to_vec(),

            include_bytes!("../../resource/01-oftonp/0時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/1時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/2時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/3時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/4時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/5時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/6時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/7時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/8時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/9時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/10時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/11時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/12時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/13時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/14時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/15時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/16時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/17時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/18時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/19時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/20時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/21時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/22時です.wav").to_vec(),
            include_bytes!("../../resource/01-oftonp/23時です.wav").to_vec(),

            include_bytes!("../../resource/02-mana/0時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/1時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/2時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/3時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/4時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/5時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/6時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/7時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/8時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/9時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/10時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/11時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/12時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/13時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/14時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/15時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/16時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/17時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/18時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/19時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/20時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/21時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/22時です.wav").to_vec(),
            include_bytes!("../../resource/02-mana/23時です.wav").to_vec(),

            include_bytes!("../../resource/03-kana/0時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/1時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/2時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/3時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/4時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/5時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/6時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/7時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/8時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/9時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/10時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/11時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/12時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/13時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/14時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/15時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/16時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/17時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/18時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/19時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/20時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/21時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/22時です.wav").to_vec(),
            include_bytes!("../../resource/03-kana/23時です.wav").to_vec(),

            include_bytes!("../../resource/04-shikokumetan/0時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/1時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/2時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/3時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/4時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/5時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/6時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/7時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/8時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/9時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/10時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/11時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/12時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/13時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/14時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/15時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/16時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/17時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/18時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/19時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/20時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/21時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/22時です.wav").to_vec(),
            include_bytes!("../../resource/04-shikokumetan/23時です.wav").to_vec(),

            include_bytes!("../../resource/05-zundamon/0時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/1時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/2時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/3時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/4時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/5時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/6時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/7時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/8時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/9時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/10時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/11時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/12時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/13時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/14時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/15時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/16時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/17時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/18時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/19時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/20時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/21時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/22時です.wav").to_vec(),
            include_bytes!("../../resource/05-zundamon/23時です.wav").to_vec(),

        ]}
    }

    pub fn get_data(&self, voice: Voice, index: usize) -> &Vec<u8> {
        return &self.data[index + (voice as usize) * 24]
    }
}
